version: '3.8'
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: savvy
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - djangonetwork

  django:
    restart: always
    build: .
    # command: python manage.py runserver 0.0.0.0:8000
    # command: gunicorn dj.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - ./staticfiles:/usr/src/app/staticfiles
      - ./media:/usr/src/app/media
    ports:
      - "8000:8000"
    depends_on:
      - db
    links:
      - db:db
    networks:
      - djangonetwork
  
  nginx:
    build: ./nginx
    volumes:
      - ./staticfiles:/usr/src/app/staticfiles
      - ./media:/usr/src/app/media
    ports:
      - "80:80"
    depends_on:
      - django
    networks:
      - djangonetwork

networks:
  default:
    driver: bridge
  djangonetwork:
    driver: bridge

volumes:
  redis_data:
